### ISSUE TITLE
Setup a monorepo for the project.

### ISSUE THREAD

**Issue by ravinduramesh** [SixthFlow-Reserach-OS/OutbreakX#3]
[Subject]

**Comment by SandipGyawali** [comment]
@ravinduramesh can i do it??

**Comment by ravinduramesh** [comment]
@SandipGyawali Sure... Thanks for your very helpful suggestions to improve this project.

**Comment by SandipGyawali** [comment]
@ravinduramesh  i will be using nx or turbo repo on of those for monorepo setup.

**Comment by ravinduramesh** [comment]
@SandipGyawali Let's go with turbo-repo as we have very few requirements at the moment.

**Comment by SandipGyawali** [comment]
@ravinduramesh #6 check the pull request.

**Comment by SandipGyawali** [comment]
#6

**Comment by ravinduramesh** [comment]
Closing the issue since the related code is merged.
