### ISSUE TITLE
Contribution Guidelines for Hacktoberfest

### ISSUE THREAD

**Issue by supekshala** [SixthFlow-Reserach-OS/OutbreakX#4]
Need to update the project's README.md to include detailed contribution guidelines specifically aimed at encouraging and assisting participants of Hacktoberfest. This will help new contributors easily get started with the project and understand how to contribute effectively.

**Comment by ravinduramesh** [comment]
Reopening since minor issues should be fixed in the guideline (ex: steps to setup the project locally).
